approve_by_comment: true
approve_regex: 'LGTM|:lgtm:|:lgtm_strong:'
reject_regex: 'reject( this)? PR|cancel( my)? LGTM|:lgtm_cancel:'
reviewers:
    required: 1
    members:
        - Thatkookooguy
        - ortichon
