approve_by_comment: true
approve_regex: '\*\*PR approved\*\*|\*\*approv(e|ing)?( this)? PR\*\*|LGTM|:lgtm:|:lgtm_strong:'
reject_regex: '\*\*reject( this)? PR\*\*|cancel( my)? LGTM|:lgtm_cancel:'
reset_on_push: true
author_approval: ignored
reviewers:
    required: 1
    members:
        - Thatkookooguy
        - ortichon
